name: Build Zephyr firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install west
        run: pip install west

      - name: Initialize workspace
        run: |
          west init -m https://github.com/HydrogreenPollub/zephyr-manifest --mr main .
          west update

      - name: Checkout application with overwrite
        uses: actions/checkout@v4
        with:
          path: zephyr-can-converter-unit
          clean: true

      - name: Setup Zephyr SDK
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: "."
          toolchains: arm-zephyr-eabi

      - name: Build
        run: |
          west build -p always zephyr-can-converter-unit

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zephyr.bin