name: Build Zephyr Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest

    steps:
      - name: Initialize workspace
        run: |
          west init -m https://github.com/HydrogreenPollub/zephyr-manifest --mr main .
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Checkout application
        uses: actions/checkout@v4
        with:
          path: zephyr-can-converter-unit
          clean: true

      - name: Build
        run: |
          west build -p always -b can_converter zephyr-can-converter-unit

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zephyr.bin